In [10]:
import numpy as np

# S10 students × 15 days
# 1 = Present, 0 = Absent
attendance_data = np.array([
    [1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1],
    [1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1],
    [0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0],
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0],
    [1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1],
    [0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0],
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
    [1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1],
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
])

num_students, num_days = attendance_data.shape

# total attendance per student
total_attendance = np.zeros(num_students)
counter = 0
for i in attendance_data:
    att = sum(i)
    total_attendance[counter] = att
    counter += 1
    

# average attendance per day
average_daily_attendance = np.zeros(num_days)
counter = 0
for j in range(num_days):
    summ = 0
    for i in attendance_data:
        summ += i[counter]
    counter += 1
    av = (summ / num_students) * 100
    average_daily_attendance[j] = av
 

# Calculate attendance percentage per student
attendance_percentage = (total_attendance / num_days) * 100

# students with attendance < 75%        
low_attendance_students = np.where(attendance_percentage < 75)[0] # returns indices

# Display results
print("Total Attendance Per Student:")
i = 1
for total in total_attendance:
    print(f"Student {i}: {total} days")
    i += 1

print("\nPercentage Attendance Per Day:")
for i, avg in enumerate(average_daily_attendance):
    print(f"Day {i+1}: {avg}%")

print("\nPercentage Attendance Per Student:")
for i, avg in enumerate(attendance_percentage):
    print(f"Student {i+1}: {round(avg,2)}%")

print("\nStudents With Attendance Below 75%:")
if len(low_attendance_students) == 0:
    print("None")
else:
    for i in low_attendance_students:
        print(f"Student {i+1} — {round(attendance_percentage[i], 2)}%")



Total Attendance Per Student:
Student 1: 13.0 days
Student 2: 11.0 days
Student 3: 5.0 days
Student 4: 15.0 days
Student 5: 11.0 days
Student 6: 10.0 days
Student 7: 8.0 days
Student 8: 14.0 days
Student 9: 10.0 days
Student 10: 15.0 days

Percentage Attendance Per Day:
Day 1: 80.0%
Day 2: 70.0%
Day 3: 80.0%
Day 4: 50.0%
Day 5: 80.0%
Day 6: 70.0%
Day 7: 70.0%
Day 8: 90.0%
Day 9: 80.0%
Day 10: 90.0%
Day 11: 70.0%
Day 12: 60.0%
Day 13: 70.0%
Day 14: 100.0%
Day 15: 60.0%

Percentage Attendance Per Student:
Student 1: 86.67%
Student 2: 73.33%
Student 3: 33.33%
Student 4: 100.0%
Student 5: 73.33%
Student 6: 66.67%
Student 7: 53.33%
Student 8: 93.33%
Student 9: 66.67%
Student 10: 100.0%

Students With Attendance Below 75%:
Student 2 — 73.33%
Student 3 — 33.33%
Student 5 — 73.33%
Student 6 — 66.67%
Student 7 — 53.33%
Student 9 — 66.67%


In [7]:
import numpy as np

In [11]:
np.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [18]:
np.save('saved_file.npy', np.eye(40))

In [20]:
a = np.load('saved_file.npy')

In [22]:
a.shape

(40, 40)

## Dictionaries

In [4]:
school_class = {}

while True:
    name = input("Enter the student's name: ")
    if name == '':
        break
    
    score = int(input("Enter the student's score (0-10): "))
    if score not in range(0, 11):
	    break
    
    if name in school_class:
        school_class[name] += (score,)
    else:
        school_class[name] = (score,)
        
for name in sorted(school_class.keys()):
    adding = 0
    counter = 0
    for score in school_class[name]:
        adding += score
        counter += 1
    print(name, ":", adding / counter)

Enter the student's name:  ali
Enter the student's score (0-10):  3
Enter the student's name:  Hamza
Enter the student's score (0-10):  3
Enter the student's name:  Ali
Enter the student's score (0-10):  4
Enter the student's name:  Harman
Enter the student's score (0-10):  6
Enter the student's name:  Zohaib
Enter the student's score (0-10):  9
Enter the student's name:  Harman
Enter the student's score (0-10):  4
Enter the student's name:  ahmad
Enter the student's score (0-10):  4
Enter the student's name:  ali 
Enter the student's score (0-10):  8
Enter the student's name:  ahmad 
Enter the student's score (0-10):  6
Enter the student's name:  ahmad
Enter the student's score (0-10):  8
Enter the student's name:  Zohaib
Enter the student's score (0-10):  6
Enter the student's name:  


Ali : 4.0
Hamza : 3.0
Harman : 5.0
Zohaib : 7.5
ahmad : 6.0
ahmad  : 6.0
ali : 3.0
ali  : 8.0


In [5]:
school_class

{'ali': (3,),
 'Hamza': (3,),
 'Ali': (4,),
 'Harman': (6, 4),
 'Zohaib': (9, 6),
 'ahmad': (4, 8),
 'ali ': (8,),
 'ahmad ': (6,)}