In [1]:
import tensorflow as tf 
import pandas as pd 
import numpy as np 
from sklearn.preprocessing import OneHotEncoder

In [2]:
file = pd.read_csv('D://Iris.csv') 

In [3]:
file.head()

sepal length  sepal width  petal length  petal width       specie
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [4]:
labels = file['specie']   
features = file.drop(['specie'], axis=1) 

In [5]:
y = np.array(labels) 
x = np.array(features) 

In [7]:
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [20]:
y.reshape(-1, 3)

array([['Iris-setosa', 'Iris-setosa', 'Iris-setosa'],
       ['Iris-setosa', 'Iris-setosa', 'Iris-setosa'],
       ['Iris-setosa', 'Iris-setosa', 'Iris-setosa'],
       ['Iris-setosa', 'Iris-setosa', 'Iris-setosa'],
       ['Iris-setosa', 'Iris-setosa', 'Iris-setosa'],
       ['Iris-setosa', 'Iris-setosa', 'Iris-setosa'],
       ['Iris-setosa', 'Iris-setosa', 'Iris-setosa'],
       ['Iris-setosa', 'Iris-setosa', 'Iris-setosa'],
       ['Iris-setosa', 'Iris-setosa', 'Iris-setosa'],
       ['Iris-setosa', 'Iris-setosa', 'Iris-setosa'],
       ['Iris-setosa', 'Iris-setosa', 'Iris-setosa'],
       ['Iris-setosa', 'Iris-setosa', 'Iris-setosa'],
       ['Iris-setosa', 'Iris-setosa', 'Iris-setosa'],
       ['Iris-setosa', 'Iris-setosa', 'Iris-setosa'],
       ['Iris-setosa', 'Iris-setosa', 'Iris-setosa'],
       ['Iris-setosa', 'Iris-setosa', 'Iris-setosa'],
       ['Iris-setosa', 'Iris-setosa', 'Iris-versicolor'],
       ['Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor'],
       ['Iri

In [11]:
encoder = OneHotEncoder(sparse_output=False) 
Y = encoder.fit_transform(y.reshape(-1,1)) 


In [12]:
Y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [22]:
x.shape[1]

(4


4

In [30]:
model = tf.keras.Sequential([ 
    tf.keras.layers.Dense(10, activation='relu', input_shape=(x.shape[1],)),        
    tf.keras.layers.Dense(8, activation='relu'), 
    tf.keras.layers.Dense(5, activation = 'relu'),
    tf.keras.layers.Dense(3, activation='softmax') 
])

In [31]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [37]:
model.fit(x, Y, epochs = 20, batch_size=1) 

Epoch 1/20
150/150 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.9549 - loss: 0.2109 
Epoch 2/20
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9602 - loss: 0.1833
Epoch 3/20
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9660 - loss: 0.1380
Epoch 4/20
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9815 - loss: 0.1191
Epoch 5/20
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9331 - loss: 0.1800
Epoch 6/20
150/150 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9598 - loss: 0.1404
Epoch 7/20
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9565 - loss: 0.1270
Epoch 8/20
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9495 - loss: 0.1449
Epoch 9/20
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9591 - loss: 0.1265
Epoch 10/20
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9899 - loss: 0.0966
Epoch 11/20
150/150 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9176 - loss: 0.1619
Epoch 12/20
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/ste

### Making predictions

In [35]:
new_sample = np.array([[1.1, 1.0, 5.4, 5.2]])   
prediction = model.predict(new_sample) 

print(prediction)
# to get exact output 
predicted_class = np.argmax(prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step
[[5.0196756e-04 8.4894471e-02 9.1460359e-01]]


In [36]:
predicted_class

2

Imagine you're learning from a book with 100 pages:

Batch size = 1: You learn and take notes after each page (slow but detailed).

Batch size = 5: You read 5 pages, then summarize and take notes.

Batch size = 100: You read the whole book before taking any notes (faster, but you might forget details).



## Convolutional neural network


In [1]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense, Flatten, Conv2D, MaxPooling2D


In [2]:
train_data = keras.utils.image_dataset_from_directory(
    directory= 'D://pets/pets/train',
    image_size = (256,256)
)


Found 132 files belonging to 2 classes.


In [3]:
train_data

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 256, 256, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None,), dtype=tf.int32, name=None))>

In [4]:
def process(image, label):
    image = tf.cast(image/255, tf.float32)
    return image, label

train_ds = train_data.map(process)


In [5]:
train_ds

<_MapDataset element_spec=(TensorSpec(shape=(None, 256, 256, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None,), dtype=tf.int32, name=None))>

In [6]:
model = Sequential()

model.add(Conv2D(32, kernel_size=(3,3), activation='relu', input_shape = (256,256,3), padding='valid'))
model.add(MaxPooling2D(pool_size = (2,2), strides=2, padding='valid'))


model.add(Conv2D(64, kernel_size=(3,3), activation='relu', padding='valid'))
model.add(MaxPooling2D(pool_size = (2,2), strides=2, padding='valid'))



model.add(Flatten())

model.add(Dense(128, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

# Softmax - multiple classes
# sigmoid - binary

D:\anaconda\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [7]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(train_ds, epochs=10)


Epoch 1/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 40s 6s/step - accuracy: 0.5591 - loss: 4.2202
Epoch 2/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 16s 3s/step - accuracy: 0.4813 - loss: 1.7838
Epoch 3/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 16s 3s/step - accuracy: 0.6910 - loss: 0.6741
Epoch 4/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 31s 5s/step - accuracy: 0.5477 - loss: 0.6375
Epoch 5/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 19s 4s/step - accuracy: 0.8157 - loss: 0.5348
Epoch 6/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 60s 13s/step - accuracy: 0.6552 - loss: 0.5869
Epoch 7/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 26s 6s/step - accuracy: 0.9364 - loss: 0.3024
Epoch 8/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 33s 6s/step - accuracy: 0.9201 - loss: 0.2668
Epoch 9/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 58s 13s/step - accuracy: 0.9442 - loss: 0.1656
Epoch 10/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 29s 5s/step - accuracy: 1.0000 - loss: 0.0625


In [8]:
import cv2 
import matplotlib.pyplot as plt 
img = cv2.imread('D://pets/pets/test/dogs/93.jpg')

img_up = cv2.resize(img, (256,256))
img_up1 = img_up.reshape((1,256,256,3))


In [9]:
model.predict(img_up1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 33s 33s/step


array([[0.]], dtype=float32)

In [10]:
# SAVING MODEL
model.save('my_model.h5')

In [12]:
# LOAD MODEL BY:
from tensorflow.keras.models import load_model
model = load_model('my_model.h5')